/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedOperacoesIndexRouteImport } from './routes/_authenticated/operacoes/index'
import { Route as AuthenticatedOperacoesIdRouteImport } from './routes/_authenticated/operacoes/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperacoesIndexRoute =
  AuthenticatedOperacoesIndexRouteImport.update({
    id: '/operacoes/',
    path: '/operacoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperacoesIdRoute =
  AuthenticatedOperacoesIdRouteImport.update({
    id: '/operacoes/$id',
    path: '/operacoes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/operacoes/': typeof AuthenticatedOperacoesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/': typeof AuthenticatedIndexRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/operacoes': typeof AuthenticatedOperacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/_authenticated/operacoes/': typeof AuthenticatedOperacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/auditoria' | '/operacoes/$id' | '/operacoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/auditoria' | '/' | '/operacoes/$id' | '/operacoes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/auditoria'
    | '/_authenticated/'
    | '/_authenticated/operacoes/$id'
    | '/_authenticated/operacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes/': {
      id: '/_authenticated/operacoes/'
      path: '/operacoes'
      fullPath: '/operacoes/'
      preLoaderRoute: typeof AuthenticatedOperacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes/$id': {
      id: '/_authenticated/operacoes/$id'
      path: '/operacoes/$id'
      fullPath: '/operacoes/$id'
      preLoaderRoute: typeof AuthenticatedOperacoesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOperacoesIdRoute: typeof AuthenticatedOperacoesIdRoute
  AuthenticatedOperacoesIndexRoute: typeof AuthenticatedOperacoesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOperacoesIdRoute: AuthenticatedOperacoesIdRoute,
  AuthenticatedOperacoesIndexRoute: AuthenticatedOperacoesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
