/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFiscalRouteImport } from './routes/_authenticated/fiscal'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCobrancaRouteImport } from './routes/_authenticated/cobranca'
import { Route as AuthenticatedCapitalRouteImport } from './routes/_authenticated/capital'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedTomadoresIndexRouteImport } from './routes/_authenticated/tomadores/index'
import { Route as AuthenticatedOperacoesIndexRouteImport } from './routes/_authenticated/operacoes/index'
import { Route as PortalOperacoesIdRouteImport } from './routes/portal/operacoes.$id'
import { Route as AuthenticatedTomadoresIdRouteImport } from './routes/_authenticated/tomadores/$id'
import { Route as AuthenticatedOperacoesNovaRouteImport } from './routes/_authenticated/operacoes/nova'
import { Route as AuthenticatedOperacoesIdRouteImport } from './routes/_authenticated/operacoes/$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiscalRoute = AuthenticatedFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCobrancaRoute = AuthenticatedCobrancaRouteImport.update({
  id: '/cobranca',
  path: '/cobranca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCapitalRoute = AuthenticatedCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTomadoresIndexRoute =
  AuthenticatedTomadoresIndexRouteImport.update({
    id: '/tomadores/',
    path: '/tomadores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperacoesIndexRoute =
  AuthenticatedOperacoesIndexRouteImport.update({
    id: '/operacoes/',
    path: '/operacoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PortalOperacoesIdRoute = PortalOperacoesIdRouteImport.update({
  id: '/operacoes/$id',
  path: '/operacoes/$id',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedTomadoresIdRoute =
  AuthenticatedTomadoresIdRouteImport.update({
    id: '/tomadores/$id',
    path: '/tomadores/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperacoesNovaRoute =
  AuthenticatedOperacoesNovaRouteImport.update({
    id: '/operacoes/nova',
    path: '/operacoes/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperacoesIdRoute =
  AuthenticatedOperacoesIdRouteImport.update({
    id: '/operacoes/$id',
    path: '/operacoes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/cobranca': typeof AuthenticatedCobrancaRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/portal/': typeof PortalIndexRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/operacoes/nova': typeof AuthenticatedOperacoesNovaRoute
  '/tomadores/$id': typeof AuthenticatedTomadoresIdRoute
  '/portal/operacoes/$id': typeof PortalOperacoesIdRoute
  '/operacoes/': typeof AuthenticatedOperacoesIndexRoute
  '/tomadores/': typeof AuthenticatedTomadoresIndexRoute
}
export interface FileRoutesByTo {
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/cobranca': typeof AuthenticatedCobrancaRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/': typeof AuthenticatedIndexRoute
  '/portal': typeof PortalIndexRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/operacoes/nova': typeof AuthenticatedOperacoesNovaRoute
  '/tomadores/$id': typeof AuthenticatedTomadoresIdRoute
  '/portal/operacoes/$id': typeof PortalOperacoesIdRoute
  '/operacoes': typeof AuthenticatedOperacoesIndexRoute
  '/tomadores': typeof AuthenticatedTomadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/capital': typeof AuthenticatedCapitalRoute
  '/_authenticated/cobranca': typeof AuthenticatedCobrancaRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/fiscal': typeof AuthenticatedFiscalRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/_authenticated/operacoes/nova': typeof AuthenticatedOperacoesNovaRoute
  '/_authenticated/tomadores/$id': typeof AuthenticatedTomadoresIdRoute
  '/portal/operacoes/$id': typeof PortalOperacoesIdRoute
  '/_authenticated/operacoes/': typeof AuthenticatedOperacoesIndexRoute
  '/_authenticated/tomadores/': typeof AuthenticatedTomadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definir-senha'
    | '/login'
    | '/portal'
    | '/auditoria'
    | '/capital'
    | '/cobranca'
    | '/compliance'
    | '/fiscal'
    | '/portal/'
    | '/operacoes/$id'
    | '/operacoes/nova'
    | '/tomadores/$id'
    | '/portal/operacoes/$id'
    | '/operacoes/'
    | '/tomadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/definir-senha'
    | '/login'
    | '/auditoria'
    | '/capital'
    | '/cobranca'
    | '/compliance'
    | '/fiscal'
    | '/'
    | '/portal'
    | '/operacoes/$id'
    | '/operacoes/nova'
    | '/tomadores/$id'
    | '/portal/operacoes/$id'
    | '/operacoes'
    | '/tomadores'
  id:
    | '__root__'
    | '/_authenticated'
    | '/definir-senha'
    | '/login'
    | '/portal'
    | '/_authenticated/auditoria'
    | '/_authenticated/capital'
    | '/_authenticated/cobranca'
    | '/_authenticated/compliance'
    | '/_authenticated/fiscal'
    | '/_authenticated/'
    | '/portal/'
    | '/_authenticated/operacoes/$id'
    | '/_authenticated/operacoes/nova'
    | '/_authenticated/tomadores/$id'
    | '/portal/operacoes/$id'
    | '/_authenticated/operacoes/'
    | '/_authenticated/tomadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiscal': {
      id: '/_authenticated/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof AuthenticatedFiscalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cobranca': {
      id: '/_authenticated/cobranca'
      path: '/cobranca'
      fullPath: '/cobranca'
      preLoaderRoute: typeof AuthenticatedCobrancaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capital': {
      id: '/_authenticated/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof AuthenticatedCapitalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tomadores/': {
      id: '/_authenticated/tomadores/'
      path: '/tomadores'
      fullPath: '/tomadores/'
      preLoaderRoute: typeof AuthenticatedTomadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes/': {
      id: '/_authenticated/operacoes/'
      path: '/operacoes'
      fullPath: '/operacoes/'
      preLoaderRoute: typeof AuthenticatedOperacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/operacoes/$id': {
      id: '/portal/operacoes/$id'
      path: '/operacoes/$id'
      fullPath: '/portal/operacoes/$id'
      preLoaderRoute: typeof PortalOperacoesIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/tomadores/$id': {
      id: '/_authenticated/tomadores/$id'
      path: '/tomadores/$id'
      fullPath: '/tomadores/$id'
      preLoaderRoute: typeof AuthenticatedTomadoresIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes/nova': {
      id: '/_authenticated/operacoes/nova'
      path: '/operacoes/nova'
      fullPath: '/operacoes/nova'
      preLoaderRoute: typeof AuthenticatedOperacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes/$id': {
      id: '/_authenticated/operacoes/$id'
      path: '/operacoes/$id'
      fullPath: '/operacoes/$id'
      preLoaderRoute: typeof AuthenticatedOperacoesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCapitalRoute: typeof AuthenticatedCapitalRoute
  AuthenticatedCobrancaRoute: typeof AuthenticatedCobrancaRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedFiscalRoute: typeof AuthenticatedFiscalRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOperacoesIdRoute: typeof AuthenticatedOperacoesIdRoute
  AuthenticatedOperacoesNovaRoute: typeof AuthenticatedOperacoesNovaRoute
  AuthenticatedTomadoresIdRoute: typeof AuthenticatedTomadoresIdRoute
  AuthenticatedOperacoesIndexRoute: typeof AuthenticatedOperacoesIndexRoute
  AuthenticatedTomadoresIndexRoute: typeof AuthenticatedTomadoresIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCapitalRoute: AuthenticatedCapitalRoute,
  AuthenticatedCobrancaRoute: AuthenticatedCobrancaRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedFiscalRoute: AuthenticatedFiscalRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOperacoesIdRoute: AuthenticatedOperacoesIdRoute,
  AuthenticatedOperacoesNovaRoute: AuthenticatedOperacoesNovaRoute,
  AuthenticatedTomadoresIdRoute: AuthenticatedTomadoresIdRoute,
  AuthenticatedOperacoesIndexRoute: AuthenticatedOperacoesIndexRoute,
  AuthenticatedTomadoresIndexRoute: AuthenticatedTomadoresIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalOperacoesIdRoute: typeof PortalOperacoesIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalOperacoesIdRoute: PortalOperacoesIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DefinirSenhaRoute: DefinirSenhaRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
